ALTER TABLE institution DROP CONSTRAINT FK_institution_ADDRESS_ADDRESSID
ALTER TABLE PATIENTMODEL DROP CONSTRAINT FK_PATIENTMODEL_ID
DROP TABLE address CASCADE
DROP TABLE institution CASCADE
DROP TABLE Person CASCADE
DROP TABLE PATIENTMODEL CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
