ALTER TABLE calendar DROP CONSTRAINT FK_calendar_INSTITUTION_INSTITUTIONID
ALTER TABLE calendartile DROP CONSTRAINT FK_calendartile_PATIENT_ID
ALTER TABLE institution DROP CONSTRAINT FK_institution_ADDRESS_ADDRESSID
DROP TABLE address CASCADE
DROP TABLE calendar CASCADE
DROP TABLE calendartile CASCADE
DROP TABLE institution CASCADE
DROP TABLE Person CASCADE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
